### ISSUE TITLE
faulthandler stdlib module requires fileno on stdout

### ISSUE THREAD

**Issue by goetzc** [bpython/bpython#628] opened 2016-07-30 19:00 UTC
Like issue #622, this one for 'fileno'.

``` python
bpython version 0.15 on top of Python 3.5.2 /usr/bin/python
>>> import pyqtgraph.examples
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import pyqtgraph.examples
  File "/usr/lib/python3.5/site-packages/pyqtgraph/examples/__init__.py", line 1, in <module>
    from .__main__ import run
  File "/usr/lib/python3.5/site-packages/pyqtgraph/examples/__main__.py", line 9, in <module>
    from . import initExample
  File "/usr/lib/python3.5/site-packages/pyqtgraph/examples/initExample.py", line 40, in <module>
    faulthandler.enable()
AttributeError: 'FakeOutput' object has no attribute 'fileno'
```

**Comment by thomasballinger** [comment] 2016-08-05 23:17
It looks like this is due to 
~~~.py
import faulthandler
faulthandler.enable()
~~~

Someone should look into what faulthandler and see what it wanted to do with fileno to see what we should do about it.
* maybe we should give it the fileno of real stdout
* maybe we should give it a new fileno it could write to that bpython could listen on

**Comment by KamilBabayev** [comment] 2016-10-28 08:02
demo

**Comment by Kashyap12** [comment] 2016-11-24 13:10
hi @thomasballinger , I am new to open source, would love to contribute

**Comment by thomasballinger** [comment] 2016-11-24 16:24
@Kashyap12, great to hear, and welcome! Would you like to take a look at this issue? You can contact me at me@ballingt.com or on freenode in #bpython if you want to talk in depth about how to get started or you have questions, or you're welcome to ask them here; @goetzc can mute this thread if it gets long ;)

The first thing you'll want to do is to try out bpython; it'll be helpful context for this issue. You can either pip install it, which would work well enough to start working on this issue, or you can follow [these instructions](http://docs.bpython-interpreter.org/contributing.html) to get a version of the source code that's easy to change on your machine.

There are a few tasks I can think of for this issue:

- [ ] Reproducing the problem by installing pygtgraph and bpython and getting this error again
- [ ] Looking at the source code for faulthandler to figure out why it needs with a fileno on stdout
- [ ] Figuring out what behavior was expected here: what does running this code in the regular Python interpreter do?
- [ ] Trying out adding in a fileno method to stdout that returns the real stdout fileno and seeing how that works

Because faulthandler is part of the standard library, we should definitely try to find a solution that makes this work. I have some ideas (main one: making a new pipe that user Python code like this can write to that we'd combine with regular `stdout.write` output) but not enough information to know if that approach is necessary.

**Comment by Kashyap12** [comment] 2016-11-24 17:59
Hi @goetzc @thomasballinger , I tried to reproduce the same issue on my bpython set up, i.e.
**bpython version 0.16 on top of Python 2.7.6 /usr/bin/python** , I pip installed pyqtgraph and then ran the below command on bpython : 
`import pyqtgraph.examples`

I got no error :)

**Comment by goetzc** [comment] 2016-11-24 23:32
FWIW, with bpython upgraded to 0.16 (and maintaining Python at 3.5.2) I don't get the error :)

**Comment by Kashyap12** [comment] 2016-11-25 09:20
@goetzc so is this issue closed?

**Comment by thomasballinger** [comment] 2016-11-25 20:32
Oh great! It looks like this was fixed by https://github.com/bpython/bpython/pull/616.

Thanks for digging into this more @Kashyap12, and thanks @goetzc for reporting and testing again!

@Kashyap12, let me know if you're interested contributing more and would like suggestions for issues. https://github.com/bpython/bpython/labels/bitesize would be a good place to start.

**Closed by thomasballinger** 2016-11-25 20:33 UTC
Labels: bitesize, help wanted
