### ISSUE TITLE
bpython doesn't with flask-sqlalchemy

### ISSUE THREAD

**Issue by LeoCHANGcn** [bpython/bpython#746] opened 2018-09-02 08:25 UTC
When I follow the book *Flask Web Development*, I found a serious issue with bpython. No error, no warning, just cannot get the expected results using bpython. For more details, check this link [flasky issue 382](https://github.com/miguelgrinberg/flasky/issues/382)

I like `bpython` because it offers auto-complete, and it worked well before. Although I don't know why bpython cannot do the flask-sqlalchemy operation correctly, switch to the original `python` can surly solve my problem. Sorry for bothering you so many times. I was stuck here for almost 2 days!!
![selection_008](https://user-images.githubusercontent.com/25730864/44953800-0dec8a80-aecb-11e8-9470-359fa06d205e.png)
![selection_009](https://user-images.githubusercontent.com/25730864/44953805-1e046a00-aecb-11e8-9cc1-3131cb470b1e.png)

**Comment by rkadam** [comment] 2019-02-07 02:24
Exactly same issue here! 

The last couple of days I've been trying to use flask_sqlalchemy with bpython and never able to see any data being added to table. After spending quite good time amount in debugging, realized that using regular python prompt, data gets added with no issues.

Any idea what can be wrong here?

**Comment by rkadam** [comment] 2019-02-07 05:11
bpython-curses is recommended workaround for this. Here is issue where I found this recommendation https://github.com/bpython/bpython/issues/741 I've tried and it works just fine in bpython-curses.

**Comment by sebastinas** [comment] 2021-12-08 17:41
Duplicate of #676.

**Closed by sebastinas** 2021-12-08 17:41 UTC
