### ISSUE TITLE
bpython 0.14.1 crash on mac after from collections import *

### ISSUE THREAD

**Issue by waynew** [bpython/bpython#537] opened 2015-05-19 14:27 UTC
I'm running bpython 0.14.1 installed via pip on Mac OSX Yosemite under Python3.4 installed via homebrew.

When I do the following:

```
$ bpython
>>> from collections import *
>>> c = C
```
When I hit that big C 

```
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsies.py", line 177, in mainloop
    process_event(e)
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsies.py", line 135, in process_event
    repl.process_event(e)
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 488, in process_event
    return self.process_key_event(e)
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 629, in process_key_event
    self.add_normal_character(e)
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 848, in add_normal_character
    self.cursor_offset += 1
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 1345, in _set_cursor_offset
    self.update_completion()
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 878, in update_completion
    self.list_win_visible = BpythonRepl.complete(self, tab)
  File "/usr/local/lib/python3.4/site-packages/bpython/repl.py", line 599, in complete
    history=self.history)
  File "/usr/local/lib/python3.4/site-packages/bpython/autocomplete.py", line 466, in get_completer_bpython
    return get_completer(BPYTHON_COMPLETER, cursor_offset, line, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/bpython/autocomplete.py", line 446, in get_completer
    cursor_offset, line, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/bpython/autocomplete.py", line 306, in matches
    matches.add(_callable_postfix(val, word))
  File "/usr/local/lib/python3.4/site-packages/bpython/autocomplete.py", line 536, in _callable_postfix
    if inspection.is_callable(value):
  File "/usr/local/lib/python3.4/site-packages/bpython/inspection.py", line 279, in is_callable
    return isinstance(obj, collections.Callable)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/abc.py", line 191, in __instancecheck__
    return cls.__subclasscheck__(subclass)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
TypeError: 'classmethod' object is not callable
```

And bpython totally crashes.

**Comment by sebastinas** [comment] 2015-05-19 14:37
Duplicate of #534. Fixed in master and 0.14-bugfix.

**Closed by sebastinas** 2015-05-19 14:37 UTC
