### ISSUE TITLE
what is s_hist

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#811] opened 2020-06-19 21:35 UTC
repl.py's Repl class has an s_hist attribute that nobody understands.

**Comment by thomasballinger** [comment] 2020-06-19 21:35
(I might look at this)

**Comment by 5aumy4** [comment] 2020-07-03 04:24
Hey! can I do some help?

**Comment by thomasballinger** [comment] 2020-07-04 15:31
Sure! @5aumy4 this task is to figure out what the s_hist attribute of the Repl class does, and to either add a comment saying what it does or to remove it. Here's where it's defined in the Repl class: https://github.com/bpython/bpython/blob/471fa8223cd10b25cbc86ee2d192d29577241d8d/bpython/repl.py#L441 
and here's where it's defined in the URWIDRepl class: https://github.com/bpython/bpython/blob/471fa8223cd10b25cbc86ee2d192d29577241d8d/bpython/urwid.py#L911

**Comment by 5aumy4** [comment] 2020-07-04 15:34
Alright!

**Comment by 5aumy4** [comment] 2020-07-13 14:00
Hey @thomasballinger ,
I researched a bit for the problem and then found out that bpython doesn't works for windows, I also tried to install linux on my laptop but I have encountered a few issues in doing so.
So it seems I can't work well on the problem. 
And I discovered this a pretty long time ago, just that I forgot to inform you about this(sorry, my bad)
So I can't work on it :( plus I think the problem is too complex for me as I am a beginner. 
I hope you find someone better than me to help you out in this.
:)

**Comment by thomasballinger** [comment] 2020-07-13 15:02
Thanks for giving it a shot, and I'm sorry bpython didn't work for you on Windows! I've heard good things about [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) and bpython should work there, although there may be a few issues there too.

**Comment by rybarczykj** [comment] 2020-08-13 18:41
It looks s_hist stores colored strings of all inputs and outputs.

here's a bpython session:
<img width="389" alt="Screen Shot 2020-08-13 at 1 37 25 PM" src="https://user-images.githubusercontent.com/48132522/90173725-7eb0a880-dd6a-11ea-924c-6faa12898d2f.png">
and here's the associated s_hist values:
<img width="646" alt="Screen Shot 2020-08-13 at 1 38 25 PM" src="https://user-images.githubusercontent.com/48132522/90173719-7ce6e500-dd6a-11ea-98f1-7b3958c7db08.png">

It's used by `redraw()` to recreate the screen when the window is resized.

Side note: Maybe the `s` in `s_hist` refers to the variable `self.s`, which seems to be cli.py's not-very-well-named equivalent of `self.current_line` in repl.py.

**Comment by rybarczykj** [comment] 2020-08-13 18:47
I'll make a PR to add a comment or two and remove it in those unused places. Maybe also rename it.

**Comment by rybarczykj** [comment] 2020-08-20 15:44
Resolved with PR #842!

**Closed** 2020-08-24 11:10 UTC
