### ISSUE TITLE
Cannot show most source code

### ISSUE THREAD

**Issue by dwt** [bpython/bpython#380] opened 2014-09-10 07:46 UTC
Some examples:

````python
   > def fnord(): pass
   > fnord<f2> # doesn't work
   > class Foo(object): pass
   > Foo<f2> # doesn't work
````
Both of these work fine in iPython. Putting these two definitions in a file and importing them yields the same result - source does not show.

These are reduced examples, in my testing I noticed that I could show the source of a whole class in my project, but I wasn't able to show most of the methods on it. Some examples: properties, decorated methods, inherited methods.

Not sure whats the reason for this, but iPython did work for those most of the time, so it may be  a good idea to fork their method source lookup code and use it instead of what is in bpython right now.

**Comment by sebastinas** [comment] 2015-01-29 20:23
This is caused by `F` in your `LESS`. Since all the examples here do not need more than a few lines to display, `less` immediately closes and `bpython` takes control again. I don't think there's anything we can do here. Detecting if `PAGER` is `less` (or something else that points `less`) seems quite fragile.

I'm closing this issue for now and will add something about it to the documentation.

**Closed by sebastinas** 2015-01-29 20:23 UTC
Labels: bug

**Comment by dwt** [comment] 2015-02-05 22:55
Out of interest, is there any reason that the bpython screen is immediately redrawn after the pager exits? If bpython would react more like my shell, then it could show the output of the pager inline until I scrolled it out of the buffer by my bpython interaction.

If I'm not mistaken, that should make bpython handle this output the same way a shell would, which should be very compatible and stable.

**Comment by thomasballinger** [comment] 2015-02-06 00:03
Hm, so maybe bpython capture stdout of less and print it out? I like thinking of all the special functionality of bpython (save, show source, open in editor, etc.) as being out-of-band; bpython is a Python interpreter with some overlays. Therefore I don't want results from these in history, I want to pretend they never happened. Curious to hear what other people think.

**Comment by dwt** [comment] 2015-02-06 11:25
I have to say that the way I use less in my shell is very much as a tool that allows me easy navigation inside a file that I'm viewing - not as something I switch to outside of the shell that is then deleted when it exits. I think that is really a different way to use pagers that could (should?) be supported by my python shell of choice.
