### ISSUE TITLE
Crash with TypeError on SIGTSTP with curtsiesfrontend

### ISSUE THREAD

**Issue by fadeopolis** [bpython/bpython#953] opened 2022-02-15 17:27 UTC
# Tested on:

* bpython version 0.22.1 on top of Python 3.8.6 (Ubuntu 18.04.6 LTS)
* bpython version 0.22.1 on top of Python 3.8.10 (Ubuntu 20.04.3 LTS inside WSL 1)

* The issue does **not** appear with bpython 0.21

# How to reproduce:

1) Start bpython
2) Either:
2.1) Press Ctrl+Z, or
2.2) send SIGTSTP to the bpython process via kill

# Output:

```
bpython version 0.22.1 on top of Python 3.8.6 /home/.../venv/bin/python3.8
>>> # press CTRL+Z
Traceback (most recent call last):
  File "/home/.../venv/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/home/.../venv/lib/python3.8/site-packages/bpython/curtsies.py", line 248, in main
    repl.mainloop(True, paste)
  File "/home/.../venv/lib/python3.8/site-packages/bpython/curtsies.py", line 175, in mainloop
    while self.module_gatherer.find_coroutine():
  File "/home/.../venv/lib/python3.8/site-packages/bpython/importcompletion.py", line 242, in find_coroutine
    next(self.find_iterator)
  File "/home/.../venv/lib/python3.8/site-packages/bpython/importcompletion.py", line 233, in find_all_modules
    for module in self.find_modules(p):
  File "/home/.../venv/lib/python3.8/site-packages/bpython/importcompletion.py", line 221, in find_modules
    for subname in self.find_modules(path_real):
  File "/home/.../venv/lib/python3.8/site-packages/bpython/importcompletion.py", line 221, in find_modules
    for subname in self.find_modules(path_real):
  File "/home/.../venv/lib/python3.8/site-packages/bpython/importcompletion.py", line 221, in find_modules
    for subname in self.find_modules(path_real):
  [Previous line repeated 2 more times]
  File "/home/.../venv/lib/python3.8/site-packages/bpython/importcompletion.py", line 201, in find_modules
    spec = finder.find_spec(name)
  File "<frozen importlib._bootstrap_external>", line 1466, in find_spec
  File "/home/.../venv/lib/python3.8/site-packages/bpython/curtsiesfrontend/repl.py", line 613, in sigtstp_handler
    self.__exit__()
TypeError: __exit__() missing 3 required positional arguments: 'exc_type', 'exc_val', and 'exc_tb'
```

# Problem:

In `bpython/curtsiesfrontend/repl.py`, function `BaseRepl.sigtstp_handler` (around line 611):
```
def __exit__(
    self,
    exc_type: Optional[Type[BaseException]],
    exc_val: Optional[BaseException],
    exc_tb: Optional[TracebackType],
) -> Literal[False]:
    # __exit__ never uses exc_type, exc_val, or exc_tb

def sigtstp_handler(self, signum, frame):
    self.scroll_offset = len(self.lines_for_display)
    self.__exit__()
    self.on_suspend()
    os.kill(os.getpid(), signal.SIGTSTP)
    self.after_suspend()
    self.__enter__()
```

`BaseRepl.sigtstp_handler` calls `BaseRepl.__exit__` without any arguments (besides self).
However, `BaseRepl.__exit__` requires the usual 3 arguments (`exc_type`, `exc_val`, `exc_tb`).

# My hacky fix:

For now I've patched my local bpython, changing the call to `self.__exit__(None, None, None)` (`__exit__` never uses its arguments anyway).

**Comment by sebastinas** [comment] 2022-02-15 20:10
Duplicate of #948.

**Closed by sebastinas** 2022-02-15 20:10 UTC
Labels: bug
