### ISSUE TITLE
Formatting fails when value-to-print is very large

### ISSUE THREAD

**Issue by BenWiederhake** [bpython/bpython#607] opened 2016-04-11 16:29 UTC
Reproduce with:
- Start bpython (happens in both `bpython version 0.15 on top of Python 3.5.1+ /usr/bin/python3` and `bpython version 0.15 on top of Python 2.7.11+ /usr/bin/python`)
- Do something that has at least *two* screenfuls of output when printed. Example: `["Hello"] * 1000`

Expected result: boring stuff. Just the printed "value" of a list that contains a thousand "hello"s.

Actual result: The value, and then some formatting related characters that got garbled:
```
>>> ["Hello"] * 1000
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello',
 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello',
[... SNIP ...]
 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello',
 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello'][-26;1H
>>>
```
Note the trailing `U+001B` which smells like formatting gone wrong.

I'm not sure whether this is a bug in xfce4-terminal 0.6.3, bpython, bpython-curtsies, curtsies, or maybe something else entirely. However, bpython is the only program exhibiting this behavior, so I reported it here.

**Comment by thomasballinger** [comment] 2016-04-12 12:14
I bet this is some nonstandard terminal formatting that curtsies is doing. I can't reproduce at the moment, but will try soon with xfce.

**Comment by thomasballinger** [comment] 2016-06-06 04:19
/me still hasn't tried with xfce

I'm guessing something's happening to the math in Curtsies such that the "Cursor Home" command that moves the cursor `<ESC>[{ROW};{COLUMN}H` came out with a negative row [here](https://github.com/thomasballinger/curtsies/blob/03552d1632b6da01a63a1a541b7a98adc4c2f665/curtsies/window.py#L456). I checked and Blessings passes through negative numbers to its Terminal.move command, so this is possible.

So probably one of the numbers in `cursor_pos[0] - offscreen_scrolls + self.top_usable_row` is bad, but I don't know which. I don't have a Linux machine around at the moment to check.

**Comment by thomasballinger** [comment] 2016-06-07 05:44
It turns out this is happening in my terminal too, but iterm swallows the invalid sequence! It's likely a Curtsies issue, these sequence may not be doing anything important, I'll look into it more.

**Comment by thomasballinger** [comment] 2016-06-13 04:54
I noticed in a gif I uploaded for another reason that the cursor disappears sometimes, and I think this may be related based on the Curtsies source: the sequence to make the cursor visible is written just after this sequence that is sometimes negative. 
![asciicast](https://cloud.githubusercontent.com/assets/458879/15997370/10709b1a-3101-11e6-903d-e5cfdb54e3dc.gif)

**Comment by thomasballinger** [comment] 2016-08-06 00:23
I suspect this is the problem but haven't nicely reproduced it. @BenWiederhake if it's not much trouble would you try `pip install git+https://github.com/thomasballinger/curtsies.git@fix-bpython-607` to see if it fixes the problem?

**Comment by BenWiederhake** [comment] 2016-08-06 08:20
Appears to work, thanks :D

(For fun I `pip uninstall`ed this version of curtsies again, as a sanity check of sorts, and indeed:  with the old system version, it still shows the faulty behavior, so your fix definitely works.)

**Comment by thomasballinger** [comment] 2016-08-07 02:52
Great, I've merged that and will do a Curtsies release before long, so at least fresh installations of Curtsies will have it fixed. I'll leave this open until I've done that Curtsies release.

**Comment by sebastinas** [comment] 2016-10-10 15:51
A new version of curtsies has been released in the meantime.

**Closed by sebastinas** 2016-10-10 15:51 UTC
