### ISSUE TITLE
Show source crashes on python 2.7 if nothing to get source of

### ISSUE THREAD

**Issue by Anthchirp** [bpython/bpython#719] opened 2017-12-07 11:27 UTC
To reproduce:
```
$ bpython
bpython version 0.16 on top of Python 2.7.13
>>> 
```

<press F2>

```python
Traceback (most recent call last):
  File "/home/wra62962/local/dials/base/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/scratch/wra62962/files/dials/base/lib/python2.7/site-packages/bpython/curtsies.py", line 190, in main
    exit_value = repl.mainloop()
  File "/scratch/wra62962/files/dials/base/lib/python2.7/site-packages/bpython/curtsies.py", line 122, in mainloop
    self.process_event_and_paint(e)
  File "/scratch/wra62962/files/dials/base/lib/python2.7/site-packages/bpython/curtsies.py", line 99, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/scratch/wra62962/files/dials/base/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1468, in paint
    1, width, self.status_bar.current_line, self.config)
  File "/scratch/wra62962/files/dials/base/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 227, in paint_statusbar
    return fsarray([func(msg.ljust(columns))[:columns]])
  File "/scratch/wra62962/files/dials/base/lib/python2.7/site-packages/curtsies/formatstring.py", line 628, in fmtstr
    string = FmtStr.from_str(string)
  File "/scratch/wra62962/files/dials/base/lib/python2.7/site-packages/curtsies/formatstring.py", line 180, in from_str
    return FmtStr(Chunk(s))
  File "/scratch/wra62962/files/dials/base/lib/python2.7/site-packages/curtsies/formatstring.py", line 70, in __init__
    raise ValueError("unicode string required, got %r" % string)
ValueError: unicode string required, got 'Nothing to get source of                                                                                                                                                                 '
```

**Comment by sebastinas** [comment] 2017-12-12 22:11
Duplicate of #642 and was fixed in 23ce07f.

**Closed by sebastinas** 2017-12-12 22:11 UTC
