### ISSUE TITLE
Pasting certain lambdas crashes bpython but not bpython-curses

### ISSUE THREAD

**Issue by pirate** [bpython/bpython#587] opened 2015-12-08 02:38 UTC
Pasting the following into bpython throws an exception deep inside Jedi code, but pasting it into bpython-curses works fine.  I posted this as a comment on a previous issue (https://github.com/bpython/bpython/issues/573), but now I think it's unrelated because of the difference between the curses and non-curses version that isn't present with the other bug.  
code to paste:
```python
funcs = {
    'mul': lambda x, y: lambda: x * y,
    'div': lambda x, y: lambda: x / y,
    'add': lambda x, y: lambda: x + y,
    'sub': lambda x, y: lambda: x - y, 
}
```
bpython traceback:
```python
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 177, in mainloop
    process_event(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 135, in process_event
    repl.process_event(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 484, in process_event
    return self.process_control_event(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 521, in process_control_event
    self.process_simple_keypress(ee)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 775, in process_simple_keypress
    self.add_normal_character(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 848, in add_normal_character
    self.cursor_offset += 1
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1345, in _set_cursor_offset
    self.update_completion()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 878, in update_completion
    self.list_win_visible = BpythonRepl.complete(self, tab)
  File "/usr/local/lib/python2.7/site-packages/bpython/repl.py", line 599, in complete
    history=self.history)
  File "/usr/local/lib/python2.7/site-packages/bpython/autocomplete.py", line 466, in get_completer_bpython
    return get_completer(BPYTHON_COMPLETER, cursor_offset, line, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/bpython/autocomplete.py", line 446, in get_completer
    cursor_offset, line, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/bpython/autocomplete.py", line 421, in matches
    history=history)
  File "/usr/local/lib/python2.7/site-packages/bpython/autocomplete.py", line 376, in matches
    completions = script.completions()
  File "/usr/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/usr/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/usr/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/usr/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/usr/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'funcs'
```

**Comment by thomasballinger** [comment] 2015-12-08 02:40
Thanks @pirate. I'll look at why the difference. If this is being a nuisance for you, you might use master for now.

**Comment by pirate** [comment] 2015-12-08 02:45
It's not a big nuisance, I can just use the curses one :)  Still loving bpython, thanks for all your hard work on it!  I introduced a few people to it at the Python SF meetup group.

**Comment by thomasballinger** [comment] 2015-12-08 02:54
I can reproduce is both bpython-curses and bpython if I type it out, I think this comes down to different paste handling when the whole thing is pasted in. Even though this crash has been fixed (and we should do a bugfix or release sometime soon) this is still interesting because it means completion is being triggered during a paste event, which seems pretty unnecessary.

**Comment by thomasballinger** [comment] 2015-12-08 03:39
Related to the previous comment, https://github.com/bpython/bpython/commit/6ab499b41daa1578131d75ed68e5d46a57a8c9e9 stops completion from running once for each character pasted. This would fix this problem, but jedi completion exceptions are already dealt with in master.

I'm closing now that I've dealt with the different between bpython and bpython-curses in pasting, but the crash in 0.14.2 is still there (#573) until we do a bugfix.

**Closed by thomasballinger** 2015-12-08 03:39 UTC
