### ISSUE TITLE
Importing pytest causes RuntimeError

### ISSUE THREAD

**Issue by ulope** [bpython/bpython#764] opened 2019-02-15 17:11 UTC
Interactively importing pytest inside bpython causes `RuntimeError: dictionary changed size during iteration`.

Steps to reproduce:

- Fresh Python 3.7.2 virtualenv
- Install bpython and pytest (currently versions `0.17.1` and `4.2.1` respectively)
- Start bpython
- Import pytest

```
○ python --version
Python 3.7.2

○ pip install pytest bpython
[...]
Installing collected packages: py, pluggy, attrs, six, more-itertools, atomicwrites, pytest, urllib3, idna, chardet, certifi, requests, typing, blessings, wcwidth, curtsies, greenlet, pygments, bpython
Successfully installed atomicwrites-1.3.0 attrs-18.2.0 blessings-1.7 bpython-0.17.1 certifi-2018.11.29 chardet-3.0.4 curtsies-0.3.0 greenlet-0.4.15 idna-2.8 more-itertools-6.0.0 pluggy-0.8.1 py-1.7.0 pygments-2.3.1 pytest-4.2.1 requests-2.21.0 six-1.12.0 typing-3.6.6 urllib3-1.24.1 wcwidth-0.1.7

○ bpython
bpython version 0.17.1 on top of Python 3.7.2 /Users/ulo/Envs/tmp-bba3a79ef1134f5f/bin/python3.7
>>> import pytest
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import pytest
  File "/Users/ulo/Envs/tmp-bba3a79ef1134f5f/lib/python3.7/site-packages/pytest.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/Users/ulo/Envs/tmp-bba3a79ef1134f5f/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 12, in <module>
    from _pytest.assertion import rewrite
  File "/Users/ulo/Envs/tmp-bba3a79ef1134f5f/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 19, in <module>
    import py
  File "/Users/ulo/Envs/tmp-bba3a79ef1134f5f/lib/python3.7/site-packages/py/__init__.py", line 153, in <module>
    'Syslog'             : '._log.log:Syslog',
  File "/Users/ulo/Envs/tmp-bba3a79ef1134f5f/lib/python3.7/site-packages/py/_vendored_packages/apipkg.py", line 63, in initpkg
    for module in sys.modules.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by ceccoemi** [comment] 2019-02-26 10:45
This bug is caused by a loop over a changing dictionary in the [py](https://github.com/pytest-dev/py) module.

This bug was fixed in the [apipkg](https://github.com/pytest-dev/apipkg) package with [this pull request](https://github.com/pytest-dev/apipkg/pull/6) but the `py` package wasn't updated.

I've opened an [issue](https://github.com/pytest-dev/py/issues/218) requesting to fix this bug even in the `py` package.

**Comment by auxiliary** [comment] 2019-08-21 14:19
This also happens when importing imblearn (tested in Python 3.7 + bpython)

**Comment by ikanobori** [comment] 2020-01-05 11:04
Just to clarify before I close both of you had this issue due to another dependency of one of the packages you used and it wasn't specific to bpython?

**Closed** 2020-04-11 18:21 UTC
